# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdf2md-tui" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "7f7d8d1bbd063f9bb49f97b1e6e9f88748dddb517a50e23931189ab30fa58ef4"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c336211530293146a09cd5c4f8de0d303cedc0baac5780df0678d1db306f458"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "150190b64825a7e99af32ce4530001c7da8f0613d0e6d4ee4d9bb9efe5b1a5df"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a790ccb6da8f73e24593d6bb47e85d79594b901d838c076d8334de536b5853fb"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pdf2md-tui"
  desc "High-performance TUI tool for batch PDF to LLM-friendly Markdown conversion"
  homepage "https://github.com/nawodyaishan/pdf2md-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdf2md-tui"

  # No zap stanza required

end
