# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdf2md-tui" do
  version "1.3.2"

  on_macos do
    on_intel do
      sha256 "ec244d88fd490b694707652cc8cd031258940ab258fb072f27dd4fc33002595e"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfeb740e7c07d6fa4ed09420a0420711d8c763aeff26fe477952b70149f7e6ad"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3673c143d36477623765b422a38953819d01b5ef6b2d9081c881287a7643daa0"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "02751c0e77f4f3531132afec349e4c2b55e42c72c9f552e0345aaadfa1568141"
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v#{version}/pdf2md-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pdf2md-tui"
  desc "High-performance TUI tool for batch PDF to LLM-friendly Markdown conversion"
  homepage "https://github.com/nawodyaishan/pdf2md-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdf2md-tui"

  # No zap stanza required

end
