# This file was generated by GoReleaser. DO NOT EDIT.
cask "usync" do
  version "1.3.7"

  on_macos do
    on_intel do
      sha256 "6937c80e30a670e32bf36ebe74b757f5037721d5f7d8b1a50f16bc5c4d47e8e2"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9853dfcee9a15ce21982394edeef2e69581a5745a68ab5a5ce93859b76ca03e"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b24f1fe2d624297c8c292f33d6c443dc2052f94243aa083d2e03b06070082e52"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32b1b9a5bdf94031979b54340785339711d6d073db9af08ab7873d235f7ebb3d"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "usync"
  desc "macOS-first developer utility for universal MCP configuration sync"
  homepage "https://github.com/nawodyaishan/universal-mcp-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usync"

  # No zap stanza required

end
