# This file was generated by GoReleaser. DO NOT EDIT.
cask "usync" do
  version "1.3.8"

  on_macos do
    on_intel do
      sha256 "5f8e5617ccab0799754cbb0a8fb77871c27dbd510dcd0dfea75a17f60185737c"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f2f23e4b47b57b76e7245cb767572e696e6c7db038cfb46e361366f926cd991"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "85ddd00d3a08e170d91e94afd141eb6ebe1bf53c1c509fb144face95c0b8235e"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1cc465606a1d17b6ac4285928a91575faefb7ade9435e0b97d6b2642a36fa5b2"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "usync"
  desc "macOS-first developer utility for universal MCP configuration sync"
  homepage "https://github.com/nawodyaishan/universal-mcp-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usync"

  # No zap stanza required

end
