# This file was generated by GoReleaser. DO NOT EDIT.
cask "usync" do
  version "1.3.10"

  on_macos do
    on_intel do
      sha256 "cfea234f073f1875f3c4437c364c798a9929d7643d05acb41fdc1dfda507812b"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b27f12a64418d4ab656ed5868c57f8eb3162b29dab918f5b1396145d3a7f644"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bd2ef03bce073d56fe9b2d3059ed4e63f4de2bdf4d34833a3f53841ca80737e2"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c834bdab95c2b94fb8eda42ea766a579e0beb299e154003cb315f551c2584287"
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v#{version}/usync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "usync"
  desc "macOS-first developer utility for universal MCP configuration sync"
  homepage "https://github.com/nawodyaishan/universal-mcp-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usync"

  # No zap stanza required

end
