# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExaMcpManager < Formula
  desc "macOS-first developer utility for wiring Exa MCP into local AI tools"
  homepage "https://github.com/nawodyaishan/mcp-config-tui"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/mcp-config-tui/releases/download/v1.0.2/exa-mcp-manager_1.0.2_darwin_amd64.tar.gz"
      sha256 "751a5931a0c4ec1ab21c210e312fdecb773834c7cb0a4d1268fb8f643424a4b1"

      define_method(:install) do
        bin.install "exa-mcp-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/mcp-config-tui/releases/download/v1.0.2/exa-mcp-manager_1.0.2_darwin_arm64.tar.gz"
      sha256 "01973859db515152c5a3387eb8bc401e8a755586c02f0da68c5fcc741227e8bf"

      define_method(:install) do
        bin.install "exa-mcp-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/mcp-config-tui/releases/download/v1.0.2/exa-mcp-manager_1.0.2_linux_amd64.tar.gz"
      sha256 "c76ed3332560479539272a52237dfb11c2923f0584d10788a09246098eba8306"
      define_method(:install) do
        bin.install "exa-mcp-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/mcp-config-tui/releases/download/v1.0.2/exa-mcp-manager_1.0.2_linux_arm64.tar.gz"
      sha256 "3faccd67bbe161ef3379d939ce16dbca9efd0b1a38dae8676a808d165a44b5d3"
      define_method(:install) do
        bin.install "exa-mcp-manager"
      end
    end
  end

  test do
    system "#{bin}/exa-mcp-manager", "--help"
  end
end
