# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Examwatch < Formula
  desc "A macOS-native pre-exam rehearsal tool for grid-unstable regions"
  homepage "https://github.com/nawodyaishan/examwatch"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/nawodyaishan/examwatch/releases/download/v1.1.0/examwatch_Darwin_x86_64.tar.gz"
    sha256 "9b6b100136d2c0cf8a0afd2b14159282ec723934a5520793b317f0f28b27b9e0"

    define_method(:install) do
      bin.install "examwatch"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/nawodyaishan/examwatch/releases/download/v1.1.0/examwatch_Darwin_arm64.tar.gz"
    sha256 "63fe1ba9d52fafe70ef0bec80be03b7a583b2dcdb12c53bc59d5344f00181adc"

    define_method(:install) do
      bin.install "examwatch"
    end
  end

  test do
    system "#{bin}/examwatch", "--help"
    system "#{bin}/examwatch", "--version"
  end
end
