# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Examwatch < Formula
  desc "A macOS-native pre-exam rehearsal tool for grid-unstable regions"
  homepage "https://github.com/nawodyaishan/examwatch"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/nawodyaishan/examwatch/releases/download/v1.0.0/examwatch_Darwin_x86_64.tar.gz"
    sha256 "543a7bd1a8ee2508844973f2d6a30875c6b1811285eba7bb2a2a15ac58812d80"

    define_method(:install) do
      bin.install "examwatch"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/nawodyaishan/examwatch/releases/download/v1.0.0/examwatch_Darwin_arm64.tar.gz"
    sha256 "1898431e1d70fd59df8e658c143a372f136ab2b2b5a04779ecf02f924655a417"

    define_method(:install) do
      bin.install "examwatch"
    end
  end

  test do
    system "#{bin}/examwatch", "--help"
    system "#{bin}/examwatch", "--version"
  end
end
