# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdf2mdTui < Formula
  desc "High-performance TUI tool for batch PDF to LLM-friendly Markdown conversion"
  homepage "https://github.com/nawodyaishan/pdf2md-tui"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.2.1/pdf2md-tui_1.2.1_darwin_amd64.tar.gz"
      sha256 "1df35361c4ce5b8760ae34ab5edbbb0d16aa78158be0aeaac351e54163e3a5da"

      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.2.1/pdf2md-tui_1.2.1_darwin_arm64.tar.gz"
      sha256 "be09d845f69658496e7d34bf4a020374bf2d8fe94fb3e81bf8602a151dd32399"

      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.2.1/pdf2md-tui_1.2.1_linux_amd64.tar.gz"
      sha256 "ce0509c304fe3d3554e9b748646a3a8bef22565e5e181a985ff5e25564d477d3"
      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.2.1/pdf2md-tui_1.2.1_linux_arm64.tar.gz"
      sha256 "b84615f97a6e1c349944b2dfb184eaf11ac65ba0e0632efe65be8a4a2e702fef"
      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
  end

  test do
    system "#{bin}/pdf2md-tui", "version"
  end
end
