# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdf2mdTui < Formula
  desc "High-performance TUI tool for batch PDF to LLM-friendly Markdown conversion"
  homepage "https://github.com/nawodyaishan/pdf2md-tui"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.0.0/pdf2md-tui_1.0.0_darwin_amd64.tar.gz"
      sha256 "3a661e8fc8c2d619ac7ca59fcd20a79ac4c1239bc4331d9eaa720a97b80df49d"

      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.0.0/pdf2md-tui_1.0.0_darwin_arm64.tar.gz"
      sha256 "a554601d7a5ef7d23f787e2fc810e45764b3952cd0288aaaafbd2f286a6b8418"

      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.0.0/pdf2md-tui_1.0.0_linux_amd64.tar.gz"
      sha256 "e9ef7ef1088c0ac9028ab3f16d3b16f05a4bd05724d36fbf0aa6e7573cfa2632"
      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/pdf2md-tui/releases/download/v1.0.0/pdf2md-tui_1.0.0_linux_arm64.tar.gz"
      sha256 "1b9d95e7dfa7ef7facdb6a4ca5d72f8d116e69318497d0735c2e20b09cf5c7c5"
      define_method(:install) do
        bin.install "pdf2md-tui"
      end
    end
  end

  test do
    system "#{bin}/pdf2md-tui", "version"
  end
end
