# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QuizSnap < Formula
  desc "Capture a screen region and paste it straight into your AI chat tab"
  homepage "https://github.com/nawodyaishan/quiz-snap"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/nawodyaishan/quiz-snap/releases/download/v1.1.0/quiz-snap_1.1.0_darwin_all.tar.gz"
  sha256 "50c4e8156564fd307c8e268d32902630c7101b0e9700302fbd0757baaf7ce968"

  define_method(:install) do
    bin.install "quiz-snap"
  end

  def caveats
    <<~EOS
      quiz-snap needs three one-time macOS permissions before it can run:

        1. Screen Recording  — required by `screencapture`
        2. Accessibility     — required to paste (Cmd+V) and submit (Return)
        3. Automation         — the first `quiz-snap run` will prompt
                                 "quiz-snap wants to control Google Chrome"
                                 (or Brave) — allow it

      Grant these under:
        System Settings -> Privacy & Security -> Screen Recording / Accessibility

      Then run:
        quiz-snap doctor
      to confirm all three are active before your first `quiz-snap configure`.
    EOS
  end

  test do
    system "#{bin}/quiz-snap", "--help"
    system "#{bin}/quiz-snap", "version"
  end
end
