# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usync < Formula
  desc "macOS-first developer utility for universal MCP configuration sync"
  homepage "https://github.com/nawodyaishan/universal-mcp-sync"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.2/usync_1.3.2_darwin_amd64.tar.gz"
      sha256 "0627c54d8159a8e6f7bd822a63a9d683da2ec837edbd7eb282c91a180a81a411"

      define_method(:install) do
        bin.install "usync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.2/usync_1.3.2_darwin_arm64.tar.gz"
      sha256 "6df58019813ecea6de3a1f5217cee187a625fc00ad079ef37b2f5aea7a04a8bb"

      define_method(:install) do
        bin.install "usync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.2/usync_1.3.2_linux_amd64.tar.gz"
      sha256 "ce1dce97dc24be340a3ba32c06d78072fd25ac759630756988f3c4bd59cdc4cd"
      define_method(:install) do
        bin.install "usync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.2/usync_1.3.2_linux_arm64.tar.gz"
      sha256 "8090a65ea21932fc80fe95a408588ed5f9896e1d087dc3b83c87c89e8be08087"
      define_method(:install) do
        bin.install "usync"
      end
    end
  end

  test do
    system "#{bin}/usync", "--help"
  end
end
