# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usync < Formula
  desc "macOS-first developer utility for universal MCP configuration sync"
  homepage "https://github.com/nawodyaishan/universal-mcp-sync"
  version "1.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.4/usync_1.3.4_darwin_amd64.tar.gz"
      sha256 "27475de075af37654c16e2856a16b928e8818c6605be41b298ef4904e3dbf58c"

      define_method(:install) do
        bin.install "usync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.4/usync_1.3.4_darwin_arm64.tar.gz"
      sha256 "68c66d538c889adf645ee359f2343b612b6cc04452dec35e16a1c14fbb2fc1d7"

      define_method(:install) do
        bin.install "usync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.4/usync_1.3.4_linux_amd64.tar.gz"
      sha256 "4a82514e123d40866329c112ba8ebd51564421e869d6aad419f96dea6c5e7f44"
      define_method(:install) do
        bin.install "usync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/universal-mcp-sync/releases/download/v1.3.4/usync_1.3.4_linux_arm64.tar.gz"
      sha256 "558b8b8179e4b1a1137262f645dfd334c32d94f0a5d13e5f355bf3dca0d39538"
      define_method(:install) do
        bin.install "usync"
      end
    end
  end

  test do
    system "#{bin}/usync", "--help"
  end
end
