# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YtTranscriptMd < Formula
  desc "Export available YouTube transcripts to Markdown"
  homepage "https://github.com/nawodyaishan/yt-transcript-md"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.5/yt-transcript-md_1.0.5_darwin_amd64.tar.gz"
      sha256 "0086f6cd196c33750c9ef36a71eacb90f44e5ac4363b10a2aae13b3ac7e4f057"

      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.5/yt-transcript-md_1.0.5_darwin_arm64.tar.gz"
      sha256 "fe1a9a0084fe18771f35fcbfc99c47b1c6a367e4877427a76a4d6df280d7ef07"

      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.5/yt-transcript-md_1.0.5_linux_amd64.tar.gz"
      sha256 "2595ca7356f30d4c4d728fb768408484bf56287deb3889aa137e8e53461d0733"
      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.5/yt-transcript-md_1.0.5_linux_arm64.tar.gz"
      sha256 "464813e8b06fa8537e4f6cebd0b1594bc625d052eac658638fb4c8279578f9b3"
      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
  end

  test do
    system "#{bin}/yt-transcript-md", "--help"
    system "#{bin}/yt-transcript-md", "version"
  end
end
