# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YtTranscriptMd < Formula
  desc "Export available YouTube transcripts to Markdown"
  homepage "https://github.com/nawodyaishan/yt-transcript-md"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.3/yt-transcript-md_1.0.3_darwin_amd64.tar.gz"
      sha256 "2e944b5804707b69666c7b2616dba057412a23efc212888b4b24f7bc2550285d"

      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.3/yt-transcript-md_1.0.3_darwin_arm64.tar.gz"
      sha256 "bb5c4a5b7ea4edc145d72517ef5d6a0d3251366d71ce0fcdbd65c3d2c9090b24"

      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.3/yt-transcript-md_1.0.3_linux_amd64.tar.gz"
      sha256 "70412dbb62ffd1ecb888604c67af64319b05f82eed2de2f01419c8e4aeb25904"
      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawodyaishan/yt-transcript-md/releases/download/v1.0.3/yt-transcript-md_1.0.3_linux_arm64.tar.gz"
      sha256 "0ed309aa5e7463d6072c1fba9d5f5a7f0b34bcb39a6d35a21de6ff45c4c1e1f4"
      define_method(:install) do
        bin.install "yt-transcript-md"
      end
    end
  end

  test do
    system "#{bin}/yt-transcript-md", "--help"
    system "#{bin}/yt-transcript-md", "version"
  end
end
